### ISSUE TITLE
What is the project status?

### ISSUE THREAD

**Issue by iav** [GeertJohan/openwrt-go#10]
@GeertJohan , what is the status of this project?
Should it work, or not?
Or, maybe,  https://github.com/brimstone/openwrt-go/tree/add-gccgo-and-libgo can be used?
Was that projects abandoned after success, or before?

**Comment by GeertJohan** [comment]
You should be able to rebase these changes on the latest openwrt. It's not actively maintained. There's an issue at OpenWRT to add support to OpenWRT itself, but it's not actively worked on by the openwrt maintainers.
