### ISSUE TITLE
Prerequisite check failed

### ISSUE THREAD

**Issue by stancox** [GeertJohan/openwrt-go#3]
Hi, I fulli noob in gcc/MIPS/edlibs etc . But I need to build an executable go binary for openwrt. Openwrt installed in virtual box. So, I start from this issue https://github.com/GeertJohan/openwrt-go/issues/2
On my macosx host I did :
> git clone https://github.com/GeertJohan/openwrt-go
> git checkout add-gccgo-and-libgo
> make menuconfig 

and after  I got

    Checking 'working-make'... ok.
    Checking 'case-sensitive-fs'... failed.
    Checking 'getopt'... failed.
    Checking 'fileutils'... failed.
    Checking 'working-gcc'... ok.
    Checking 'working-g++'... ok.
    Checking 'ncurses'... ok.
    Checking 'zlib'... ok.
    Checking 'gawk'... failed.
    Checking 'unzip'... ok.
    Checking 'bzip2'... ok.
    Checking 'perl'... ok.
    Checking '/usr/bin/python2.7'... ok.
    Checking 'wget'... ok.
    Checking 'git'... ok.
    Checking 'gnutar'... failed.
    Checking 'svn'... ok.
    Checking 'openssl'... ok.
    Checking 'gnu-find'... failed.
    Checking 'getopt-extended'... ok.
    Checking 'file'... ok.
    Checking 'non-root'... ok.

    Build dependency: OpenWrt can only be built on a case-sensitive filesystem
    Build dependency: Please install GNU getopt
    Build dependency: Please install GNU fileutils
    Build dependency: Please install GNU awk.
    Build dependency: Please install GNU tar.
    Build dependency: Please install GNU find

    Prerequisite check failed. Use FORCE=1 to override.
    make: *** [tmp/.prereq-build] Error 1

What I did wrong?

**Comment by Akagi201** [comment]
read this http://wiki.openwrt.org/doc/howto/buildroot.exigence

**Comment by GeertJohan** [comment]
What @Akagi201 sais. Your machine requires tools to compile openwrt. The tutorial behind the link should get you through it :+1:

**Comment by stancox** [comment]
Thanx, but I have last question. Maybe, I'm not understand main/full conception.
I'm stuck on "OpenWrt Buildroot – Installation on Mac OS X" (http://wiki.openwrt.org/doc/howto/buildroot.exigence.macosx)  paragraph 4
>follow the Linux instructions starting with Downloading Sources

Ok, I clone git repo (git clone git://git.openwrt.org/openwrt.git) and what next ? Why I need copy of git openwrt repo in my host machine(macosx) if I have VirtualBox machine with already installed openwrt(Barrier Breaker) ?

I'm fully stuck :(

**Comment by GeertJohan** [comment]
Ah, you need to compile a new openWRT image and install that on a new virtualbox machine.
You need the new image because you require eglibc (by default µlibc is used, afaik). Go requires eglibc.
So you need to follow the build instructions, and when you're in menuconfig apply these settings: https://github.com/GeertJohan/openwrt-go/issues/2#issuecomment-77829053

**Comment by Dhouha-ma** [comment]
i have this problem could any one helps me with ?

admin@dhouha:~/openwrt$ sudo make menuconfig 
Checking 'working-make'... ok.
Checking 'case-sensitive-fs'... ok.
Checking 'getopt'... ok.
Checking 'fileutils'... ok.
Checking 'working-gcc'... ok.
Checking 'working-g++'... ok.
Checking 'ncurses'... ok.
Checking 'zlib'... ok.
Checking 'gawk'... ok.
Checking 'flex'... ok.
Checking 'unzip'... ok.
Checking 'bzip2'... ok.
Checking 'patch'... ok.
Checking 'perl'... ok.
Checking 'python'... ok.
Checking 'wget'... ok.
Checking 'git'... ok.
Checking 'gnutar'... ok.
Checking 'svn'... failed.
Checking 'gnu-find'... ok.
Checking 'getopt-extended'... ok.
Checking 'non-root'... failed.

Build dependency: Please install the subversion client.
Build dependency: Please do not compile as root.

Prerequisite check failed. Use FORCE=1 to override.
make: **\* [tmp/.prereq-build] Error 1

**Comment by akharon** [comment]
do not **"Build dependency: Please do not compile as root."** use sudo :)
