### ISSUE TITLE
openwrt-go/tools/scons/Makefile PKG_MD5SUM is not correct!!!

### ISSUE THREAD

**Issue by educationaccount** [GeertJohan/openwrt-go#5]
openwrt-go/tools/scons/Makefile
PKG_NAME:=scons
PKG_VERSION:=2.3.5
...
## PKG_MD5SUM:=a8988c7ef11133bb3b6ccf0af67ce010

correct：PKG_MD5SUM:=8b0d1041266f89b18e47f26d943f8aa5

**Comment by GeertJohan** [comment]
I think this should be fixed in openwrt upstream..
This repository is just here to publish required changes to add go to the build system.

**Comment by educationaccount** [comment]
Yes,I See!

Is this diff link?
https://github.com/GeertJohan/openwrt-go/compare/master...add-gccgo-and-libgo.diff

**Comment by GeertJohan** [comment]
Yes, that's the diff.

There's an issue open at openwrt to add golang, but it's not very active :(
https://dev.openwrt.org/ticket/18611

**Comment by educationaccount** [comment]
Use this diff, I succeeded.

Thank you！

**Comment by GeertJohan** [comment]
No problem, have fun!
