### ISSUE TITLE
Make fails due to MD5 mismatch with scons-2.3.5.tar.gz

### ISSUE THREAD

**Issue by einsteinx2** [GeertJohan/openwrt-go#6]
I'm trying to compile based on the info in the other issue, but I keep running into a make failure due to this mismatch. Here's the output from the failure:

MD5 sum of the downloaded file does not match (file: 8b0d1041266f89b18e47f26d943f8aa5, requested: a8988c7ef11133bb3b6ccf0af67ce010) - deleting download.

It's trying to download it from http://colocrossing.dl.sourceforge.net/project/scons/scons/2.3.5/scons-2.3.5.tar.gz and the other mirrors it tries after 404.

Any ideas?

**Comment by cxjava** [comment]
The same problem for me

**Comment by cxjava** [comment]
@einsteinx2  merge the [Openwrt master branch](https://github.com/openwrt-mirror/openwrt) into this branch , it will be fixed for this bug.

**Comment by flyingbing** [comment]
the makefile file is under openwrt-go/tools/scons/Makefile, you can change the MD5SUM val from a8988c7ef11133bb3b6ccf0af67ce010  to  8b0d1041266f89b18e47f26d943f8aa5, try it again

**Comment by miao1007** [comment]
change md5 fixed.

**Comment by iav** [comment]
Just got this error, 13 marth, 2016. 
@miao1007 why you are sure this bug fixed?
Seems no one try to build world since 10 Oct 2015?

**Comment by miao1007** [comment]
Maybe the versions in the makefile is to late than the mirror.

I edited the makefile's md5 to 8b0d1041266f89b18e47f26d943f8aa5, and it works.

**Comment by GeertJohan** [comment]
PR merged.
